# Generated by Django 3.0.3 on 2020-02-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to='movie')),
                ('category', models.CharField(choices=[('C', 'COMEDY'), ('R', 'ROMANCE'), ('D', 'DRAMA'), ('A', 'ACTION')], max_length=1)),
                ('year_of_production', models.DateField()),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
