# Generated by Django 3.0.3 on 2020-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20200220_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('romance', 'ROMANCE'), ('comedy', 'COMEDY'), ('action', 'ACTION'), ('drama', 'DRAMA')], max_length=10),
        ),
    ]
