# Generated by Django 3.0.3 on 2020-02-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20200221_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('comedy', 'COMEDY'), ('action', 'ACTION'), ('drama', 'DRAMA'), ('romance', 'ROMANCE')], max_length=10),
        ),
    ]
