# Generated by Django 3.0.3 on 2020-02-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20200223_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('mw', 'Most Watched'), ('tr', 'Top Rated'), ('ra', 'Recently Added')], default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('romance', 'ROMANCE'), ('comedy', 'COMEDY'), ('drama', 'DRAMA'), ('action', 'ACTION')], max_length=10),
        ),
    ]
