# Generated by Django 3.0.3 on 2020-02-23 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20200223_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='commments',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='commments',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('drama', 'DRAMA'), ('romance', 'ROMANCE'), ('comedy', 'COMEDY'), ('action', 'ACTION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('ra', 'Recently Added'), ('tr', 'Top Rated'), ('mw', 'Most Watched')], max_length=2),
        ),
    ]
