# Generated by Django 3.0.3 on 2020-02-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20200223_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('romance', 'ROMANCE'), ('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY')], max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('tr', 'Top Rated'), ('mw', 'Most Watched'), ('ra', 'Recently Added')], max_length=2),
        ),
    ]
